export const best_hotels = [
  { id: 33, name: "Secrets Mallorca Villamil Resort & Spa", stars: 5 },
  { id: 59, name: "Sheraton Mallorca Arabella Golf Hotel", stars: 5 },
  { id: 64, name: "Maria Eugenia Pension", stars: 5 },
  { id: 65, name: "Hotel de Mar Gran Melia", stars: 5 },
  { id: 67, name: "Gran Meliá Victoria", stars: 5 },
  { id: 70, name: "Allsun Hotel Bella Paguera", stars: 5 },
  { id: 71, name: "Allsun Hotel Cormoran", stars: 5 },
  { id: 82, name: "Allsun Hotel Bahia del Este", stars: 5 },
  { id: 106, name: "Serrano Palace", stars: 5 },
  { id: 113, name: "Allsun Hotel Borneo", stars: 5 },
  { id: 135, name: "Allsun Hotel Sumba", stars: 5 },
  { id: 144, name: "Hotel Morlans", stars: 5 },
  { id: 146, name: "FERGUS Style Cala Blanca Suites", stars: 5 },
  { id: 149, name: "FERGUS Style Tobago", stars: 5 },
];
