export const best_hotels = [
  { id: 33, name: "Secrets Mallorca Villamil Resort & Spa", stars: 5 },
  { id: 59, name: "Sheraton Mallorca Arabella Golf Hotel", stars: 5 },
  { id: 64, name: "Maria Eugenia Pension", stars: 5 },
  { id: 65, name: "Hotel de Mar Gran Melia", stars: 5 },
  { id: 67, name: "Gran Meliá Victoria", stars: 5 },
  { id: 70, name: "allsun Hotel Bella Paguera", stars: 5 },
  { id: 71, name: "allsun Hotel Cormoran", stars: 5 },
  { id: 82, name: "allsun Hotel Bahia del Este", stars: 5 },
  { id: 106, name: "Serrano Palace", stars: 5 },
  { id: 113, name: "allsun Hotel Borneo", stars: 5 },
  { id: 135, name: "allsun Hotel Sumba", stars: 5 },
  { id: 144, name: "Hotel Morlans", stars: 5 },
  { id: 146, name: "FERGUS Style Cala Blanca Suites", stars: 5 },
  { id: 149, name: "FERGUS Style Tobago", stars: 5 },
  { id: 162, name: "HM Ayron Park", stars: 5 },
  { id: 173, name: "Universal Grand León & Spa", stars: 5 },
  { id: 181, name: "MySeaHouse Hotel Flamingo", stars: 5 },
  { id: 183, name: "Pure Salt Garonda", stars: 5 },
  { id: 207, name: "Metropolitan Playa Hotel", stars: 5 },
  { id: 9, name: "Bonsol Hotel Resort & Spa", stars: 5 },
];
