const departure_airports = [
  { value: "AMS", label: "Amsterdam" },
  { value: "BSL", label: "Basel" },
  { value: "BER", label: "Berlin" },
  { value: "BLL", label: "Billund" },
  { value: "BRE", label: "Bremen" },
  { value: "BRU", label: "Brussels" },
  { value: "CRL", label: "Brussels Charleroi" },
  { value: "CSO", label: "Cochstedt" },
  { value: "CGN", label: "Cologne" },
  { value: "DTM", label: "Dortmund" },
  { value: "DRS", label: "Dresden" },
  { value: "DUS", label: "Dusseldorf" },
  { value: "NRN", label: "Düsseldorf Weeze" },
  { value: "EIN", label: "Eindhoven" },
  { value: "ERF", label: "Erfurt" },
  { value: "FRA", label: "Frankfurt" },
  { value: "HHN", label: "Frankfurt-Hahn" },
  { value: "FDH", label: "Friedrichshafen" },
  { value: "GVA", label: "Geneva" },
  { value: "GOT", label: "Gothenburg" },
  { value: "GRZ", label: "Graz" },
  { value: "HAM", label: "Hamburg" },
  { value: "HAJ", label: "Hannover" },
  { value: "INN", label: "Innsbruck" },
  { value: "FKB", label: "Karlsruhe/Baden-Baden" },
  { value: "KSF", label: "Kassel" },
  { value: "KRK", label: "Krakow" },
  { value: "LEJ", label: "Leipzig" },
  { value: "LNZ", label: "Linz" },
  { value: "LBC", label: "Lübeck" },
  { value: "LUX", label: "Luxembourg" },
  { value: "FMM", label: "Memmingen" },
  { value: "MUC", label: "Munich" },
  { value: "FMO", label: "Münster/Osnabrück" },
  { value: "NUE", label: "Nuremberg" },
  { value: "PAD", label: "Paderborn/Lippstadt" },
  { value: "PRG", label: "Prague" },
  { value: "SCN", label: "Saarbrücken" },
  { value: "SZG", label: "Salzburg" },
  { value: "SXB", label: "Strasbourg" },
  { value: "VIE", label: "Vienna" },
  { value: "WAW", label: "Warsaw" },
  { value: "GWT", label: "Westerland" },
  { value: "ZRH", label: "Zurich" },
];
